# fly.toml app configuration file generated for leaf-chat on 2023-06-01T21:01:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leaf-chat"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  CHAT_FILES_SERVER_HOST = "https://leaf-chatfiles-backend.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
